version: '2'
services:
  nginx:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: newhost=newhost
    #  io.rancher.container.network: true
    image: rajeshworld/first:new
    ports:
      - "5050:80"
